[package]
name = "wfslab"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }

[dev-dependencies]
oorandom = "11.1.5"
