[package]
name = "wfinlinevec"
version = "0.1.0"
edition = "2024"

[features]
bytemuck = ["dep:bytemuck"]

[lints]
workspace = true

[dependencies]
bytemuck = { version = "1.24.0", features = ["derive"], optional = true }
